language: perl
before_install:
  - export PATH=/opt/rakudo/bin:$PATH
  - cat /dev/zero | ssh-keygen -q -N ""
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod og-wx ~/.ssh/authorized_keys
install:
    - export PATH=/opt/rakudo/bin:$PATH
    - wget https://github.com/nxadm/rakudo-pkg/releases/download/2017.03_02/perl6-rakudo-moarvm-ubuntu16.04_20170300-02_amd64.deb
    - dpkg -i *.deb
    - install_zef_as_user.sh
    - ~/.perl6/zef install Sparrowdo
script:
  - sparrowdo --bootstrap --host=127.0.0.1
